name: Build Release and Debug of Meme Downloader 2022 For Windows and Linux

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build
      id: date
      run:  |
        chmod +x Build.sh && \
        ./Build.sh && \
        echo "::set-output name=today::$(date +"%d-%m-%y--%H-%M-%S")"
    
    - name: Upload Windows && Linux Release and Debug
      uses: softprops/action-gh-release@v1
      with:
        files: |
            /home/runner/work/Meme-Downloader-2022/Meme-Downloader-2022/build/Meme Downloader 2022.exe
            /home/runner/work/Meme-Downloader-2022/Meme-Downloader-2022/build/DEBUG-Meme Downloader 2022.exe
            /home/runner/work/Meme-Downloader-2022/Meme-Downloader-2022/build/Linux-Meme Downloader 2022
            /home/runner/work/Meme-Downloader-2022/Meme-Downloader-2022/build/Linux-DEBUG-Meme Downloader 2022
        name: Meme Downloader 2022 Auto-Build
        tag_name: "${{ steps.date.outputs.today }}--Win"
